### ISSUE TITLE
Default admin.conf file for kubectl initial config

### ISSUE THREAD

**Issue by blkwtch** [elik1001/coreos-kubernetes-generator#14]
hi
i followed your [tutorial](https://www.devtech101.com/2018/12/26/coreos-kubernetes-configuration-generator-now-supports-kubernetes-1-13-rbac-bootstrapping-more/) and was able to successfully install the cluster which consists of 3 master nodes(so far).
right now i am having issues finding the admin.conf file which allows to perform administration tasks on the cluster.
do you have any idea on where to get that. and i think it will be better to include it in the ignition file

**Comment by elik1001** [comment]
Hi.


So kubectl on the 3 master node(s) should work if all the environment files are set correctly using the ssl keys, please let me know if not. 

However, accessing the cluster from outside, for example from a worker node or if rbac is enabled, with curent configration that will require a certiface.

Please take a look on the below post how to configure / enable rbac, and how to configure access. The post was not written for CoreOS however the configuration is similar. 

https://www.devtech101.com/2018/08/24/enabling-configuring-rbac-tls-node-bootstrapping-on-an-existing-kubernetes-cluster-part-7/

Of course you can generate an admin.conf(which I don't think I documented), however in the grand scheme of things, you would be better off configuring rbac. I might try to update that once I return.


P.s. I have limit access until new year, I will try to assist best as I can.


I hope you enjoy reading my blog,
Wishing you the best,

Eli

**Comment by blkwtch** [comment]
Hi

Thanks for your answer. Correct me if I am mistaken but normally and right
after a master node is provisioned I should be able to find the admin.conf
file in this location  /etc/kubernetes/admin.conf
Which is my main concern at the moment.

**Comment by elik1001** [comment]
Hi,

Let me try to explain, the admin.conf concept comes from the "kubeadm" utility which is primarily used, to create a single control-plane cluster very quickly, however, with simplicity (sometimes) comes compromises, in this case you have less control on how your cluster is configured (i.e for example ip range), hence that's the reason someone would use the CoreOS auto-configuration.

in the case were you use the "kubeadm" to create your demo cluster it will auto-generate for you access, roles, etc. with that is also generates (or gives you to option to) generate an admin.conf.

You can read more about this here -  Google documentation reference to "kubeadm".
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

However, in my example(s) I specifically did not use the "kubeadm", for various reasons. some of the benefits are.

At time of this post, kubeadm did not have the option for full multi master cluster (I believe its still limited).
You have full control on network structure ip, ssl, roles, access, etc...

Now, you can still mimic / create an admin.conf file, more on that below...

The general cluster administration like "kubectl get.." should work as root without any configuration required, the configuration transpiler has been pre-configured to populate all configuration files with the SSL certificates required to access the cluster. however, this dose not configure / enable RBAC, to configure your cluster with RBAC / access controls, please check this post which was written for CentOS but the configuration would be very similar.
Enabling, Configuring RBAC, TLS Node Bootstrapping On An Existing Kubernetes Cluster – Part 7.
https://www.devtech101.com/2018/08/24/enabling-configuring-rbac-tls-node-bootstrapping-on-an-existing-kubernetes-cluster-part-7/

# As root - the below commend should return cluster details, does it not work for you?
kubectl get pv,pvc,pods --all-namespaces
NAME                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM             STORAGECLASS    REASON   AGE

To use an admin.conf (like) file for cluster access (outside of your root user) without RBAC configuration, please try the below.
Lets test if the kubeconfig.yaml (admin.conf) we are going to use works, run the below to verify.

# In my current CentOS cluster the kubeconfig location is "/etc/kubernetes/pki/kubeconfig.yaml", in the configuration you are using I believe its in "/etc/kubernetes/worker-kubeconfig.yaml" 
kubectl --kubeconfig /etc/kubernetes/pki/kubeconfig.yaml get nodes
NAME          STATUS     ROLES    AGE    VERSION
dc2-coreos1   Ready      <none>   326d   v1.13.2
dc2-coreos2   Ready      <none>   326d   v1.13.2
dc2-coreos3   Ready      <none>   326d   v1.13.2

if you look in the file it would look something like the below.
-------
          apiVersion: v1
          kind: Config
          clusters:
          - name: local
            cluster:
              server: https://10.0.2.11:443
              certificate-authority: /etc/kubernetes/ssl/ca.pem
          users:
          - name: kubelet
            user:
              client-certificate: /etc/kubernetes/ssl/worker.pem
              client-key: /etc/kubernetes/ssl/worker-key.pem
          contexts:
          - context:
              cluster: local
              user: kubelet
-------------------
Note: these certificate(s) were auto-generated before installation.

Of curse its not advisable (and safe) to use the general cluster SSL key to access the cluster. for that I would recommend configuring RBAC.
I have a full write-up on this - Enabling, Configuring RBAC, TLS Node Bootstrapping On An Existing Kubernetes Cluster – Part 7.
https://www.devtech101.com/2018/08/24/enabling-configuring-rbac-tls-node-bootstrapping-on-an-existing-kubernetes-cluster-part-7/

If you do choose to use the worker-kubeconfig.yaml, you can just copy that to your home folder as admin.conf.

# To check the config
kubectl config view --kubeconfig /etc/kubernetes/pki/kubeconfig.yaml

Help configuring access to your cluster.
https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

P.S. The configuration you are using was configured using Kubernetes version 1.8  - 1.13, I have not had a chance to re-test with latest versions. my recent versions are mostly using CentOS, please do let me corrections, so I can update and others will befit, I am always happy to learn.
Last, I do have a Docker image that might help you play with the configuration.

I hope this helps.
Eli

**Comment by blkwtch** [comment]
Hi Eli
thanks a lot for your detailed answer.
i was mistaken when i said that the cluster is up and running. 
looks like it's an SSL issue ...
> `-- Logs begin at Tue 2019-12-31 11:24:47 UTC. --
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.036842     935 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: nodes "coreos1" is forbidden: User "etcd-node" cannot list resource "nodes" in API group "" at the cluster scope
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.037999     935 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: pods is forbidden: User "etcd-node" cannot list resource "pods" in API group "" at the cluster scope
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.071979     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.172283     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.272637     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.372989     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.473527     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.573976     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.674340     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.774792     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.875159     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:35 coreos1 kubelet-wrapper[935]: E1231 12:55:35.975575     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.035913     935 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: services is forbidden: User "etcd-node" cannot list resource "services" in API group "" at the cluster scope
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.037982     935 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: nodes "coreos1" is forbidden: User "etcd-node" cannot list resource "nodes" in API group "" at the cluster scope
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.039078     935 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: pods is forbidden: User "etcd-node" cannot list resource "pods" in API group "" at the cluster scope
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.075903     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.176113     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.276321     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.377004     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.477363     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.577734     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.678190     935 kubelet.go:2266] node "coreos1" not found
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: I1231 12:55:36.696093     935 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: I1231 12:55:36.698568     935 kubelet_node_status.go:446] Recording NodeHasSufficientMemory event message for node coreos1
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: I1231 12:55:36.698753     935 kubelet_node_status.go:446] Recording NodeHasNoDiskPressure event message for node coreos1
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: I1231 12:55:36.698859     935 kubelet_node_status.go:446] Recording NodeHasSufficientPID event message for node coreos1
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: I1231 12:55:36.698995     935 kubelet_node_status.go:72] Attempting to register node coreos1
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.701031     935 kubelet_node_status.go:94] Unable to register node "coreos1" with API server: nodes is forbidden: User "etcd-node" cannot create resource "nodes" in API group "" at the cluster scope
Dec 31 12:55:36 coreos1 kubelet-wrapper[935]: E1231 12:55:36.778402     935 kubelet.go:2266] node "coreos1" not found
^C`

**Comment by blkwtch** [comment]
and this is what i get when 
`core@coreos1$ kubectl --kubeconfig /etc/kubernetes/pki/kubeconfig.yaml get nodes`

> Error from server (Forbidden): nodes is forbidden: User "etcd-node" cannot list resource "nodes" in API group "" at the cluster scope

Here's the content of kubeconfig file
```
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://10.0.0.4:443
    certificate-authority: /etc/kubernetes/ssl/ca.pem
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/etcd-node.pem
    client-key: /etc/kubernetes/ssl/etcd-node-key.pem
contexts:
- context:
    cluster: local
    user: kubelet
```
