### ISSUE TITLE
indexing bug in 0.8.5

### ISSUE THREAD

**Issue by MrSmiths** [elik1001/coreos-kubernetes-generator#15]
Please enter the new value for 23: (default: worker3.example.com): blabla.blabla.com
-----------------------------------------------------------
[?] Would you like to "add" CN/Host Names (alt names) ? (y/N): y

Traceback (most recent call last):
  File "./generate_template.py", line 696, in <module>
    if (int(srv_cert_list.keys()[-1])+1) < 10:
TypeError: 'dict_keys' object does not support indexing
root@5c3c6ffb02ba:/kub-generator#

**Comment by elik1001** [comment]
Should be fixed in the latest master, please test and report back the results.

**Comment by MrSmiths** [comment]
solved! thanks!
