### ISSUE TITLE
resulting ignition file contains references to a http_proxy server that doesn't exist

### ISSUE THREAD

**Issue by dgranville** [elik1001/coreos-kubernetes-generator#3]
After generating my ignition file and building a CoreOS server, I discovered the etcd-member service kept failing with the error "run: discovery failed".  After checking the server's network settings and doing some troubleshooting, I discovered the ignition file set the http_proxy environment variable to a service running at http://10.10.20.20:8080 which doesn't exist in my environment.  This resulted in rkt being unable to pull the images for etcd (and presumably other services).

**Comment by elik1001** [comment]
You are right.
This is part of the reason I didn't push an update.

Most of my work was done behind a proxy, and I discovered many issues
related to the way proxy is currently set.
I am in the work of changing this. being busy with many other things.

In the mean time, if you are not using a proxy you can simply remove it,
run the below to find all files containing http_proxy set.
find /etc -type f |xargs grep http_proxy

P.S. I plan to updated the default to no http proxy, with an option to
overwrite.

**Comment by elik1001** [comment]
Fixed in latest build  Version 0.2, now committed to master.
