### ISSUE TITLE
resulting ignition file doesn't install kubectl

### ISSUE THREAD

**Issue by dgranville** [elik1001/coreos-kubernetes-generator#4]
After taking the generated ignition file and building a CoreOS Linux Container server with it, I discovered I didn't have an easy way to test the functioning of kubernetes because kubectl wasn't installed.  I installed it manually using the following commands:

curl -O https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl
chmod a+x kubectl
mkdir -p /opt/bin
mv kubectl /opt/bin/.

**Comment by elik1001** [comment]
Fixed in latest build  Version 0.2, now committed to master.
