### ISSUE TITLE
Cant be run in standard python docker

### ISSUE THREAD

**Issue by JHoelzel** [elik1001/coreos-kubernetes-generator#6]
Hey i tried to take a look at your script today with the the official docker python image but got an error on first try so i thought i'd let you know.

`Status: Downloaded newer image for python:latest
root@3331d8a4ce2d:/# cd /var/coreosscript/
root@3331d8a4ce2d:/var/coreosscript# ./generate_template.py
  File "./generate_template.py", line 441
    \n-----------------------------------------------------------'
                                                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Verifying required python modules \
\n-----------------------------------------------------------')?`

`docker run --rm -ti -v d:/coreos-kubernetes-generator-master:/var/coreosscript python bash `
same with alpine image;
`docker run --rm -ti -v d:/coreos-kubernetes-generator-master:/var/coreosscript jfloff/alpine-python bash `

best,
Johannes

**Comment by JHoelzel** [comment]
Also tried my luck with the jfloff/alpine-python image. same result

**Comment by elik1001** [comment]
Sorry for the issue, unfortunately I  am away till Apr 9th with no access
to to check .
In the meantime I hope you will find a workaround, please updated if you
can get it to work so I can fix the code.
P.S. All my work was done on Ubuntu 17.
Thank you,
Eli

**Comment by elik1001** [comment]
Sorry for the delay.

The issue you were having is related to the script being _Python 2.x_ only comparable.

I am happy to let you know that the script is now been updated to work in Python 3.x.

Since I have limited time for testing, please test and let me know if you run in to any issues.
For the time being please use branch _Version-05_ as the updated has not (yet) been committed to master.

Thank you,
Eli

**Comment by elik1001** [comment]
I ran additional testing, and it seems to be working, so I committed  Version-05 to the Master branch.
Closing this issue as fixed in latest commit.

**Comment by JHoelzel** [comment]
Sorry i would have tested this on the weekend =)

Thanks for updating it!
